### ISSUE TITLE
What data was used by the pretrained model of LibriTTS？

### ISSUE THREAD

**Issue by jiaweiru** [facebookresearch/AudioDec#10]
Hello, thank you for your excellent open source work。
Could you please provide information about the subsets that were utilized during the training of the 24kHz model?
For instance, were subsets like train-clean-100, train-clean-360, or other subsets used?

**Comment by bigpon** [comment]
Hi,
Yes! we used the whole train-clean-360 set and partial train-clean-100 set (excluded 'train-clean-100/1*/*/*.wav' and 'train-clean-100/2*/*/*.wav').
