### ISSUE TITLE
The test results are different from those in the paper

### ISSUE THREAD

**Issue by WzyCrush** [facebookresearch/AudioDec#12]
I tested `clean_testset_wav` audio in the Valentini dataset according to the description in your paper. The model used is `vctk_v1`, and the test results are as follows
![test_result](https://github.com/facebookresearch/AudioDec/assets/97033869/6fc7f549-55ff-45df-969a-0302aeb252f4)
The test results are quite different from those in your paper. Can you release the calculation code?

**Comment by bigpon** [comment]
Hi, 
The evaluation codes are mostly from the [sprocket-vc](https://github.com/k2kobayashi/sprocket/tree/master) repo.

We used their [feature extractor](https://github.com/k2kobayashi/sprocket/blob/master/sprocket/speech/feature_extractor.py) to extract f0, u/v segments and mcep.
We used their [melcd function](https://github.com/k2kobayashi/sprocket/blob/master/sprocket/util/distance.py) to calculate MCD.
Since the WORLD vocoder is sensitive to speaker differences, we set different f0 search ranges for the two test speakers. If you don't carefully set them, it usually results in higher f0 extraction errors. 
Please refer to their [example](https://github.com/k2kobayashi/sprocket/blob/master/docs/vc_example.md) to correctly extract the features.

Moreover, for F0RMSE, we only calculate the voiced segments.  
Based on your results, I assume you calculate the F0RMSE of the whole utterance (including both voiced and unvoiced parts).

For the MCD part, we first conduct VAD to remove the silence parts and calculate it excluding the energy term which is the first dimension of mcep. If you directly calculate the whole utterance's MCD (including the silence parts), it tends to result in a much lower MCD.

**Comment by LiangChaoHu** [comment]
Hi, thank you very much for your response. I followed the instructions you provided to perform the following operations:

1. Draw histograms of p232 and p257 according to the [example](https://github.com/k2kobayashi/sprocket/blob/master/docs/vc_example.md), and determine the F0min and F0max of p232 and p257 based on the histograms. Set F0min and F0max of p232 to 40 and 240, respectively, and set F0min and F0max of p257 to 40 and 390, respectively. The histogram is shown below.
2. Use the `webrtcvad`  to detect the unvoiced segments in the audio files (including the original audio file and the reconstructed audio file), and then remove the unvoiced segments. The example below shows an instance of removing unvoiced segments(audio file waveform diagram).
3. Calculate the F0 of the original audio and the reconstructed audio(removed the unvoiced segments audio) based on F0min and F0max, and then calculate the F0RMSE.

My calculated results are still significantly different from those in the paper. I used the `webrtcvad` to implement VAD. Is there any  problem with this step?  Could you tell me how you implemented VAD? If there are any problems with the entire calculation process, please tell me.
**![直方图](https://github.com/facebookresearch/AudioDec/assets/97033869/5fe68ea8-2af0-4c00-a2f8-2dfb4e819fdb)**
![wave](https://github.com/facebookresearch/AudioDec/assets/97033869/01026a89-1fad-479d-ab8c-326bc19f9b84)

**Comment by bigpon** [comment]
Hi, 
according to the figures, the correct f0 search range of P232 should be around 70 -240 Hz, and that of P257 should be 140-340.
The f0 extractor is not perfect and most real f0 should follow one Gaussian distribution.
Therefore, the other peaks in the figures should be taken as the wrong extracted f0.
Please check the tutorial in the Sprocket repo carefully.

I also used the VAD provided by the Sprocket repo, which requires handcraft setting the power threshold. Please refer to their tutorial, too.

I used the VAD to get the voice/unvoice indexes of the ground truth audio and calculated the results of the voiced segment only.

"webrtcvad" only filters out the silence parts but still keeps some unvoiced speech.
Imperfectly filtering out silence parts will also cause degradation of the f0 extraction.

**Comment by WzyCrush** [comment]
Hi, 
Thank you very much for your reply. 
I set the F0 search range of P232 to 70-240Hz and P257 to 140-340Hz. I regard the part where F0 is equal to 0 as unvoiced segment, and the non-zero part as voiced segment. The U/V errors calculation results are as follows. 

F0RMSE is calculated using the parts of both the original audio and the reconstructed audio that are voiced segments. The calculation results are as follows.

Use the [get_alignment()](https://github.com/k2kobayashi/sprocket/blob/master/example/src/estimate_twf_and_jnt.py) function in the Sprocket repo to calculate the MCD. The power threshold uses the default value -20 in the function. The calculation results are as follows.
![image](https://github.com/facebookresearch/AudioDec/assets/97033869/0a006a1f-60fa-4f78-a67a-4253ce442018)

There may be some errors in my calculation process, and the calculation results are still different from those shown in the paper.
Thanks again for your reply.

**Comment by bigpon** [comment]
Hi,
the power threshold should be adjusted according to the statistical results (The tutorial has mentioned how to do it.)

My settings were
p232:
  f0_max: 240
  f0_min: 65
  pow_th: -22
p257:
  f0_max: 390
  f0_min: 120
  pow_th: -15


For MCD calculations,
I first get the speech and silence indexes of the reference (natural) utterance by VAD.
I use the VAD index for both generated and reference mel-ceptra (mcep).
I perform DTW of them and make the generated ones align with the reference.
The first dimension of mcep (the power) is excluded from the MCD calculations.

The settings of mcep extraction were

sampling_rate: 48000       # Sampling rate.
fft_size: 2048             # FFT size.
hop_size: 240              # Hop size.
win_length: 2048           # Window length.
                           # If set to null, it will be the same as fft_size.
window: "hann"             # Window function.
shiftms: 5                 # Frame shift (ms)
mcep_dim: 49               # Mcep dim
highpass_cutoff: 70        # Cutoff frequency of preprocessing highpass filter
mcepshift: 1

**Comment by WzyCrush** [comment]
Hi
Thank you very much for your reply.

I followed the settings you mentioned to extract “f0” and “mcep”.

For the MCD calculations, I first get the speech indexes via VAD and then the speech mceps via the indexes. Then align mecp through DTW, and finally calculate MCD(the first dimension of mcep has been excluded). The calculated result of MCD is 4.76, which is still different from the result in the paper.

In the sprocket-vc, I did not find the code for time-warping the speech indexes of f0. Does the alignment of f0 also use DTW?

I determined the U/V segments through the extracted f0, and I extracted f0 according to the settings you mentioned, but the calculated U/V error is 10.56%. The  result is different from this in the paper.

There may still be errors in some of the details of my calculations. It would be greatly appreciated if you could release your evaluation codes.

**Comment by bigpon** [comment]
Hi, 
As I mentioned in point 3, I used the time-warping results of the mcc for f0 alignment.
WORLD feature extractions include some randomness, so the results may be slightly different in different devices.

P.S. We might not be able to open source the code that is not mostly written by ourselves because Meta has some open-source protocols.

**Comment by Hezhiyao** [comment]
> I tested `clean_testset_wav` audio in the Valentini dataset according to the description in your paper. The model used is `vctk_v1`, and the test results are as follows ![test_result](https://github.com/facebookresearch/AudioDec/assets/97033869/6fc7f549-55ff-45df-969a-0302aeb252f4) The test results are quite different from those in your paper. Can you release the calculation code?

Hello, I'm using the DNSMOS model from the following link for evaluation:
https://github.com/microsoft/DNS-Challenge/tree/master/DNSMOS
I'm also using the clean_test_wav dataset. Why is my DNSMOS score only around 3.4-3.5? I'd be very grateful if you could provide an explanation.
