### ISSUE TITLE
download link. needs. more. juice.

### ISSUE THREAD

**Issue by ryanrussell** [facebookresearch/AudioDec#2]
Hey,

Looks great. Unfortunately, the download link is already down.. and you're only at 185 stars. I don't see this getting any better :)

Any chance you can put the exp.zip on an s3 bucket or somewhere that can handle the downloads?

Thanks!

```bash
wget https://ghe.oculus-rep.com/yichiaowu/AudioDec/releases/download/pretrain_models/exp.zip
--2023-05-19 02:49:34--  https://ghe.oculus-rep.com/yichiaowu/AudioDec/releases/download/pretrain_models/exp.zip
Resolving ghe.oculus-rep.com (ghe.oculus-rep.com)... 54.193.191.239, 2600:1f1c:aad:f800:8c1d:af6a:f7b6:ead3
Connecting to ghe.oculus-rep.com (ghe.oculus-rep.com)|54.193.191.239|:443... failed: Connection timed out.
Connecting to ghe.oculus-rep.com (ghe.oculus-rep.com)|2600:1f1c:aad:f800:8c1d:af6a:f7b6:ead3|:443... failed: Network is unreachable.
```

**Comment by bigpon** [comment]
Hi,
The link is fixed now.
The pre-trained models are upload to the releases of this repo, so you also can access them via the releases page (https://github.com/facebookresearch/AudioDec/releases).
