### ISSUE TITLE
quantizer dropout

### ISSUE THREAD

**Issue by a897456** [facebookresearch/AudioDec#20]
Hi @bigpon 
Does AudioDec retain the quantizer dropout strategy of SoundStream?
How?

**Comment by a897456** [comment]
Hi @bigpon 
Could you spare some time to help me with this problem which means a lot to me. THS

**Comment by bigpon** [comment]
We don't implement the quantizer dropout in AudioDec.

**Comment by a897456** [comment]
> We don't implement the quantizer dropout in AudioDec.

        for layer in self.layers:
            i = i + 1
            if i > num_codebook(Calculated from bit rate)
                return
