### ISSUE TITLE
LibriTTS dataset

### ISSUE THREAD

**Issue by a897456** [facebookresearch/AudioDec#21]
![image](https://github.com/facebookresearch/AudioDec/assets/28752526/e983e9e2-62fa-422c-b208-8c8b60dfe26d)
Hi @bigpon 
For your `libritts_sym` model, does the dataset include `train-clean-100` and `train-clean-360` and `train-other-500`? Or just part of it?
Because it's related to the training time.

**Comment by bigpon** [comment]
Please refer to #10

**Comment by a897456** [comment]
> Please refer to #10

ok THS
