### ISSUE TITLE
Trying to train a low bitrate version

### ISSUE THREAD

**Issue by McFlyy21** [facebookresearch/AudioDec#24]
Hello! I want to train a 1.6kbps AudioDec model for 16khz sample rate data, according to the bitrate settings in the paper, I modified the codebook_num in symAD_vctk_48000_hop300.yaml from 8 to 3 and modified the sample rate from 48000 to 16000, does this modification match the rules?

**Comment by bigpon** [comment]
Hi,
Yes.

The bit rate is
(sampling_rate / down_sampling_scale (the product of enc_strides/dec_strides))*(log_2 codebook_size)*codebook_num.

Therefore, if you don't change the enc_strides/dec_strides and codebook_size, your bit rate is
(16000/300)*(10)*3 = 1600 bps (16 kbps)

**Comment by McFlyy21** [comment]
Thank you for your reply!
