### ISSUE TITLE
Table 4 and 5

### ISSUE THREAD

**Issue by a897456** [facebookresearch/AudioDec#25]
Excuse me again
1. Table 4 and Table 5 in your paper are about `Latency`. What are the units of the numbers in the table?RTF?
2. There seems to be no mention of the comparison of audiodec model sizes in the paper? Can the model size be calculated in the code?

**Comment by bigpon** [comment]
Hi,
1. It is the processing time in milliseconds (ms), which can be found in the table's caption.
2. No, we don't provide the code to calculate the number of learnable parameters. However, you can easily find it on the official Pytorch website.

**Comment by a897456** [comment]
> 2. No, we don't provide the code to calculate the number of learnable parameters. However, you can easily find it on the official Pytorch website.

Sorry, I did not find something, can you help me?
