### ISSUE TITLE
Speaker ID for real-time VC 

### ISSUE THREAD

**Issue by karthik19967829** [facebookresearch/AudioDec#28]
Hi Authors,
    Thank you for the great open-source work. I wanted to check if would it be feasible to add a speaker ID to HifiGAN decoder to be able to enable swapping it in inference time to enable real-time VC ?

**Comment by bigpon** [comment]
Hi,
since the audio code/latent includes much speaker-related information, directly adding a speaker ID embedding as the input to the HiFiGAN will easily be ignored by the HiFiGAN network.

The possible solution is to use another network to further disentangle the speaker-dependent and -independent components of the audio code before the HiFiGAN network.

**Comment by karthik19967829** [comment]
Thank you for the response , do you have any pointers for the above implementation? 

Do you think training from scratch on any to one  VC task , might make decoder adapt to generate speech in a certain voice ?

**Comment by bigpon** [comment]
I haven't tried any VC framework using the AudioDec latent.

However, I think it is worth taking a SOTA VC open-source repo using mel-spectrogram/log-spectrogram as the I/O and replacing the mel-spectrogram with the AudioDec latent.

For training an any-to-one model using AudioDec, the main problem is the requirements of length-aligned parallel source and target data, which is not easy to get.
Even if you get the parallel source and target data, aligning them in at least the AudioDec latent domain is also challenging.

**Comment by karthik19967829** [comment]
<img width="599" alt="Screen Shot 2024-06-11 at 2 24 10 PM" src="https://github.com/facebookresearch/AudioDec/assets/35610230/5f79d6f5-54e0-49c2-a5f0-7bb40d7b6c28">
https://arxiv.org/pdf/2401.11053 I am working on implementing this paper that uses audioDec as acoustic token and streaming conformer based content representation as bottle neck feature to make the translation easier 

Lmk your thoughts , overall seems a bit too complicated but the inductive bias of different components is pretty good
