### ISSUE TITLE
How to obtain the encoded file

### ISSUE THREAD

**Issue by XiangSheng0607** [facebookresearch/AudioDec#29]
Hello, author, thank you for your great work. I want to use your open source code to test socket transmission. Deploy the encoder on one computer and the decoder on another computer. I would like to ask how to obtain the features of your stream model after encoding so that I can transfer it to another computer. Thank you very much for your answer.

**Comment by bigpon** [comment]
Hi, 
please refer to 
https://github.com/facebookresearch/AudioDec/blob/main/demoStream.py
and
https://github.com/facebookresearch/AudioDec/blob/main/utils/audiodec.py

We did simulate the behavior in the demo.
