### ISSUE TITLE
Multi-GPU training

### ISSUE THREAD

**Issue by jiaweiru** [facebookresearch/AudioDec#3]
Hello, thank you for your open source work. I have a question about this code, whether it can be trained using multiple GPUs. It seems that there is no option to set the GPU in the code.

**Comment by bigpon** [comment]
Hi,
since the computation cost is not high, we don't implement the multi-GPU training.
If you need a multi-GPU version, I would like to recommend you modify the code following the  Parallel WaveGAN repo (https://github.com/kan-bayashi/ParallelWaveGAN).

**Comment by jiaweiru** [comment]
> Hi, since the computation cost is not high, we don't implement the multi-GPU training. If you need a multi-GPU version, I would like to recommend you modify the code following the Parallel WaveGAN repo (https://github.com/kan-bayashi/ParallelWaveGAN).

Thank you very much for your answer
