### ISSUE TITLE
HiFiGAN is not supported for the analyzer?

### ISSUE THREAD

**Issue by a897456** [facebookresearch/AudioDec#31]
https://github.com/facebookresearch/AudioDec/blob/5ec3ab9d53cff2f4d92163c0624a277d173703a5/codecTrain.py#L258-L263

https://github.com/facebookresearch/AudioDec/blob/5ec3ab9d53cff2f4d92163c0624a277d173703a5/config/vocoder/AudioDec_v1_symAD_libritts_24000_hop300_clean.yaml#L24-L26

    raise NotImplementedError(f"Model type: {model_type} is not supported for the analyzer!")
NotImplementedError: Model type: HiFiGAN is not supported for the analyzer!

Hi@bigpon 
Is there a contradiction？？？

**Comment by bigpon** [comment]
Hi, HiFiGAN is a vocoder/decoder, which converts the latent back to waveform.
For an analyzer, we use symAD.

https://github.com/facebookresearch/AudioDec/blob/5ec3ab9d53cff2f4d92163c0624a277d173703a5/codecTrain.py#L254-L255

**Comment by a897456** [comment]
Hi@bigpon 
Have you ever tried to replace Hifigan with Diffwave?

**Comment by bigpon** [comment]
No, we didn't but we did tried diffusion-based generative model. The details can be found in our latest work [ScoreDec](https://arxiv.org/abs/2401.12160).

**Comment by a897456** [comment]
> No, we didn't but we did tried diffusion-based generative model. The details can be found in our latest work [ScoreDec](https://arxiv.org/abs/2401.12160).

Very Nice, bigpon.
And has the code of ScoreDec been made public currently?

**Comment by bigpon** [comment]
Because we directly take the code from [SGMSE](https://github.com/sp-uhh/sgmse), we do not have any plan to release the code of ScoreDec.
However, it is very easy to train a ScoreDec post-filter using their code. The only thing you have to do is preparing the training data by yourself (codec-natural pairs).

**Comment by a897456** [comment]
> Because we directly take the code from [SGMSE](https://github.com/sp-uhh/sgmse), we do not have any plan to release the code of ScoreDec. However, it is very easy to train a ScoreDec post-filter using their code. The only thing you have to do is preparing the training data by yourself (codec-natural pairs).

OK, bigpon, I will have a try. Thank you for your repaly.
