### ISSUE TITLE
[metrics] ViSQOL

### ISSUE THREAD

**Issue by a897456** [facebookresearch/AudioDec#34]
HI @bigpon 
By the way: I found that DNSMOS was used in your paper, but it seems that VISQOL was not used, and even MUSHRA was not used. These two metrics should be very important. Why didn't you use them? It's okay if it's not convenient for you to answer.

**Comment by bigpon** [comment]
Hi,
Although ViSQOL support 48kHz, it only supports general audio, which is not suitable for measuring speech quality. 

MUSHRA is highly recommended. MOS only can give you a rough idea. If the differences between your system and baselines are subtle, MUSHRA is a better way to evaluate them.

**Comment by a897456** [comment]
Hi @bigpon 
https://github.com/descriptinc/descript-audio-codec/blob/main/scripts/mushra.py
I haven't tested MUSHRA yet. Do you think running the above `mushra.py` file will do? Or are there other testing methods?

**Comment by bigpon** [comment]
Hi,
We have an internal tool to do it.
I don't know the details of DAC's MUSHRA but they mention that their subjective tests are MUSHRA-like in their paper.
