### ISSUE TITLE
Denoise training

### ISSUE THREAD

**Issue by a897456** [facebookresearch/AudioDec#37]
Hi, @bigpon 
Bigpon, I don't understand the passage you mentioned. Could you please explain it in detail?

For the denoise training, we only have to update the encoder so the 2-stage training is unnecessary.
Since you train the model w/o GAN using 500k iterations, you have to take \exp\autoencoder\symAD_vctk_8000_hop240\ **checkpot-500000Steps.pkl as the initial and train the encoder for another 500k iterations under the denoise training.

_Originally posted by @bigpon in https://github.com/facebookresearch/AudioDec/issues/32#issuecomment-2240932270_

**Comment by bigpon** [comment]
Hi, 
in denoising, you can update only the encoder while fixing the codebook and decoder.
Please check the submit_denoise.sh and the corresponding config for the details.

**Comment by a897456** [comment]
https://github.com/facebookresearch/AudioDec/blob/9cc4e58aa684c96a1a299f38a7085e2426d20ad4/submit_denoise.sh#L65-L72
However, lines 67 and 68 in `submit_denoise.sh` make it hard to believe that the model is being trained. Instead, it seems like the model is being tested.

**Comment by bigpon** [comment]
Hi, can you check the script details before asking the question? stage 0 is the training part, and stage 2 is the testing part.

**Comment by a897456** [comment]
I am so sorry, I am a newbie. Please forgive my ignorance.
