### ISSUE TITLE
Increasing batch length 

### ISSUE THREAD

**Issue by anton-jeran** [facebookresearch/AudioDec#6]
Thank you for sharing the code.

If we increase the batch_length (9600) and adv_batch_length (9600) to longer duration e.g., 48000.

![s1](https://github.com/facebookresearch/AudioDec/assets/73730558/6c7e0948-0bd9-43a7-93f0-9cee905df356)

Do we need to change anything else to transmit data at 12kbps. Do we need to modify code_dim?
![s2](https://github.com/facebookresearch/AudioDec/assets/73730558/1cc663e6-79f3-4193-b820-0d82ec835a51)

**Comment by bigpon** [comment]
Hi,
You don’t need to modify other parameters when increasing the batch_length or adv_batch_length.

Actually, the larger batch_length (for training AE w/ only metric losses) usually results in better performance, especially in the denoising case. Therefore, we use 2s (96000) batch_length for the denoising training. 

However, we also found that the larger adv_batch_length (for training the model w/ both metric and adversarial losses) will not improve the performance but significantly increase the training time. Therefore, we will recommend increasing only the batch_length and keeping the adv_batch_length the same.

**Comment by anton-jeran** [comment]
Thanks for the clarification :)
